services:
  - type: web
    name: libreria-sistema-backend
    plan: free
    runtime: docker
    repo: https://github.com/pisarana/libreria-sistema
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
