databases:
  - name: libreria-db
    databaseName: libreria_db
    user: libreria_user
    plan: free

services:
  - type: web
    name: libreria-sistema-backend
    plan: free
    runtime: docker
    repo: https://github.com/pisarana/libreria-sistema
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: libreria-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: libreria-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: libreria-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
